# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubCom/willyv3/nextjsTemplater < Formula
  desc "github.com/WillyV3/nextjs-templater"
  homepage "https://github.com/WillyV3/nextjs-templater"
  version "0.1.46"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_darwin_amd64.tar.gz"
      sha256 "030706827eea0941929b8e158f87c5344d9609eabbab025162e8dd5460a821c5"

      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_darwin_arm64.tar.gz"
      sha256 "071ae2093a728db6b267c866df1d35b1198e91656f06ff2a09e937a9850851c7"

      def install
        bin.install "nextjs-templater"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_linux_amd64.tar.gz"
      sha256 "4f793b47b3c84d0f18876b9f7ee8f5bf1d3a61a2630757eec832c32fc1bc8f62"
      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_linux_arm64.tar.gz"
      sha256 "54d769bacb383c151f141298e4a23abe5f62c2833c3a34c118727091eb104386"
      def install
        bin.install "nextjs-templater"
      end
    end
  end

  test do
    system "#{bin}/github.com/WillyV3/nextjs-templater", "--version"
  end
end
