# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubCom/willyv3/nextjsTemplater < Formula
  desc "github.com/WillyV3/nextjs-templater"
  homepage "https://github.com/WillyV3/nextjs-templater"
  version "0.1.46"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_darwin_amd64.tar.gz"
      sha256 "d6fd5f3e10a9d95173c0554115fcf94b600eb04b94bca636bf93b3a55fcc86c6"

      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_darwin_arm64.tar.gz"
      sha256 "c45ebd37a7bbb216095c0e7d89efda92306aad478f8dca9d815a37f718439edb"

      def install
        bin.install "nextjs-templater"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_linux_amd64.tar.gz"
      sha256 "158fa392332839e46440a3c89abdd5e45410b490773f4dd7e5b3cec05e8c7e32"
      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.1.46/nextjs-templater_0.1.46_linux_arm64.tar.gz"
      sha256 "6879b69c4fca2ed3873d8195da403a58854f3c1c748c211ee5958e78f44bb051"
      def install
        bin.install "nextjs-templater"
      end
    end
  end

  test do
    system "#{bin}/github.com/WillyV3/nextjs-templater", "--version"
  end
end
