# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubCom/willyv3/nextjsTemplater < Formula
  desc "github.com/WillyV3/nextjs-templater"
  homepage "https://github.com/WillyV3/nextjs-templater"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.2.1/nextjs-templater_0.2.1_darwin_amd64.tar.gz"
      sha256 "b630b2fe2db727254b3e8a291ef9eb9ffa718bd0e6c36f13df3a49d81d030d67"

      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.2.1/nextjs-templater_0.2.1_darwin_arm64.tar.gz"
      sha256 "fecc0edc06295552c1873abd2a3a617af4812d338cee0ba0640635036ec36119"

      def install
        bin.install "nextjs-templater"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.2.1/nextjs-templater_0.2.1_linux_amd64.tar.gz"
      sha256 "5669b276c0ec6931551f8be47429f6735de273d928c994f141d6d4a309fb2ec7"
      def install
        bin.install "nextjs-templater"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/nextjs-templater/releases/download/v0.2.1/nextjs-templater_0.2.1_linux_arm64.tar.gz"
      sha256 "7f6fb92adf7bbab56a31dbd7de03fd9eb664357a01c6901c2fd622db3589c18d"
      def install
        bin.install "nextjs-templater"
      end
    end
  end

  test do
    system "#{bin}/github.com/WillyV3/nextjs-templater", "--version"
  end
end
