# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubCom/willyv3/vinwWorkspace < Formula
  desc "github.com/willyv3/vinw-workspace"
  homepage "https://github.com/WillyV3/vinw-workspace"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.3/vinw-workspace_0.0.3_darwin_amd64.tar.gz"
      sha256 "f75edb8b976287bbbf2a2d2806d10ada11fb19e82ef54b6678b273085dd1729c"

      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.3/vinw-workspace_0.0.3_darwin_arm64.tar.gz"
      sha256 "05421d40f50e68bed617b44d0eb91278be5bbdfacd19061f728b7ddfa313601b"

      def install
        bin.install "vinw-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.3/vinw-workspace_0.0.3_linux_amd64.tar.gz"
      sha256 "766abf7c8ae5afcc973bc5468c9de27e11d56e177c5e41b655d52bbfc32834f4"
      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.3/vinw-workspace_0.0.3_linux_arm64.tar.gz"
      sha256 "2ae3b1b3975e05d7274f0f8e526f8cf7b0c0ad56da2a390da6c25e436be83327"
      def install
        bin.install "vinw-workspace"
      end
    end
  end

  test do
    system "#{bin}/github.com/willyv3/vinw-workspace", "--version"
  end
end
