# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distui < Formula
  desc "distui"
  homepage "https://github.com/willyv3/distui"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/willyv3/distui/releases/download/v0.0.7/distui_0.0.7_darwin_amd64.tar.gz"
      sha256 "3500ee9cbe9d8f9456313d47af47b909c97e7d166e7d6ab469275ade3dbe93a7"

      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/willyv3/distui/releases/download/v0.0.7/distui_0.0.7_darwin_arm64.tar.gz"
      sha256 "96bffb7bc7aa676e3484b54b71d74cea614b23f37211c6c1008c86195e81ffd1"

      def install
        bin.install "distui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.7/distui_0.0.7_linux_amd64.tar.gz"
      sha256 "46767ce369f528d035a4b0d4d8857a4ae9b80e33057981c62e28d630e2aaae42"
      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.7/distui_0.0.7_linux_arm64.tar.gz"
      sha256 "eb1177a338d242041bc0a5f8c387b317053e8d73fc2d4d747ee6cb611111a9e3"
      def install
        bin.install "distui"
      end
    end
  end
end
