# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudePeersV2 < Formula
  desc "Channel-native peer messaging network for AI coding agents (broker + TUI)"
  homepage "https://github.com/WillyV3/claude-peers-v2"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.1/claude-peers-v2_0.1.1_darwin_amd64.tar.gz"
      sha256 "9e06e8dd8bb8cc7bae26f47d6c99e31c9d88a2a1b20ee0ee2bda1e282b68ee6f"

      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.1/claude-peers-v2_0.1.1_darwin_arm64.tar.gz"
      sha256 "2f9b581520241cf5feee090761926decfded3902ae6f5a796bacaaa477d59757"

      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.1/claude-peers-v2_0.1.1_linux_amd64.tar.gz"
      sha256 "d2fe8bacf02d9c103572a509da626c946253f6ca4c682e7940be114aaf959e81"
      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.1/claude-peers-v2_0.1.1_linux_arm64.tar.gz"
      sha256 "a5f0bb6966c84f39d34355d268e324a4e022d0527e0f26e720c2463938f624a8"
      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
  end

  test do
    system "#{bin}/cpv2", "version"
  end
end
