# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudePeersV2 < Formula
  desc "Channel-native peer messaging network for AI coding agents (broker + TUI)"
  homepage "https://github.com/WillyV3/claude-peers-v2"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.0/claude-peers-v2_0.1.0_darwin_amd64.tar.gz"
      sha256 "1d57fdaaff58d054ddfaa8076511f32b4d7e2062f4e5ef20d22a58badd86134c"

      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.0/claude-peers-v2_0.1.0_darwin_arm64.tar.gz"
      sha256 "c6569be5bcd507bce9bc41b4528953206b574b55b550632b2171184781e998df"

      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.0/claude-peers-v2_0.1.0_linux_amd64.tar.gz"
      sha256 "a8f0796109b482907518981d0d27ef7ad4120bff7e20a7a86ee5f314b42b22b8"
      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/claude-peers-v2/releases/download/v0.1.0/claude-peers-v2_0.1.0_linux_arm64.tar.gz"
      sha256 "9f6ce81506080b775419408c968eac31c79838b8c5e4e6939fb16854a53f2173"
      define_method(:install) do
        bin.install "cpv2"
        bin.install "cpv2-tui"
      end
    end
  end

  test do
    system "#{bin}/cpv2", "version"
  end
end
