# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cp3 < Formula
  desc "Peer network for coding agents — one binary, embedded server, injects into live TUIs"
  homepage "https://github.com/WillyV3/cp3"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.1/cp3_0.2.1_darwin_amd64.tar.gz"
      sha256 "7510febc9450b6004381d7abb1ab96b07ae755d080030ccb1009527599159654"

      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.1/cp3_0.2.1_darwin_arm64.tar.gz"
      sha256 "35f1a6fa8e446276a08bbddc8ebd564eab4a3e823365291e308b0819d223925a"

      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.1/cp3_0.2.1_linux_amd64.tar.gz"
      sha256 "7082bca49b19b466091a2dc82d6f142a964d25a1c0624a4b587bc21699a231ec"
      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.1/cp3_0.2.1_linux_arm64.tar.gz"
      sha256 "7b983a3fff57c8d6534fb3abfdc083f91150e003fbcb57d27cc441654b9f2965"
      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:  cp3 setup   (wires Claude Code MCP + statusline)
      Tip: `cp3 statusline` prints a live peers segment — append it to a
      custom statusline if you have one. `cp3 doctor` diagnoses anything.
    EOS
  end

  test do
    system "#{bin}/cp3", "doctor"
  end
end
