# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cp3 < Formula
  desc "Peer network for coding agents — one binary, embedded server, injects into live TUIs"
  homepage "https://github.com/WillyV3/cp3"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.0/cp3_0.2.0_darwin_amd64.tar.gz"
      sha256 "b90ec5a1f668bf81620b078954cb5df4fc0b1f8387157212bc47bbd027b04b1d"

      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.0/cp3_0.2.0_darwin_arm64.tar.gz"
      sha256 "7906e0e575f0d0f7da34b9306cdd56d677de555dc15098bfc226bb218e3dd60c"

      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.0/cp3_0.2.0_linux_amd64.tar.gz"
      sha256 "ad82ca4aedcb8da62b7a8883cefc5a0e0f8b7464545702b296575ad340b6dace"
      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.2.0/cp3_0.2.0_linux_arm64.tar.gz"
      sha256 "8a25d5d099cf11d02e51b19d8a66dae224dcd32f9687d87d60bb1ab63eaf6f38"
      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:  cp3 setup   (wires Claude Code MCP + statusline)
      Tip: `cp3 statusline` prints a live peers segment — append it to a
      custom statusline if you have one. `cp3 doctor` diagnoses anything.
    EOS
  end

  test do
    system "#{bin}/cp3", "doctor"
  end
end
