# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cp3 < Formula
  desc "Peer network for coding agents — one binary, embedded server, injects into live TUIs"
  homepage "https://github.com/WillyV3/cp3"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/cp3/releases/download/v0.1.0/cp3_0.1.0_darwin_amd64.tar.gz"
      sha256 "5d8c102fa1200e6be3ddfd68eb977a0f18db07209f9ddc47b1c43aed21fca743"

      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/cp3/releases/download/v0.1.0/cp3_0.1.0_darwin_arm64.tar.gz"
      sha256 "aba882b490f0f12c3132874c4cb8132669797e61713347114002b3c05fe2490c"

      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.1.0/cp3_0.1.0_linux_amd64.tar.gz"
      sha256 "a23ddc1a7c1202602e32d1b4954275a757b54fb23cc5ef7507be523d8f2b0bae"
      define_method(:install) do
        bin.install "cp3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/cp3/releases/download/v0.1.0/cp3_0.1.0_linux_arm64.tar.gz"
      sha256 "fcfa21136635b862661068d285f0da600d2f4bc36b6cfe2da25a509af18a54aa"
      define_method(:install) do
        bin.install "cp3"
      end
    end
  end

  test do
    system "#{bin}/cp3", "doctor"
  end
end
