# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distui < Formula
  desc "distui"
  homepage "https://github.com/willyv3/distui"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/willyv3/distui/releases/download/v1.0.8/distui_1.0.8_darwin_amd64.tar.gz"
      sha256 "3767f769d92059415ab0536fd5edfe1218e179b94125317271b02beb94b37400"

      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/willyv3/distui/releases/download/v1.0.8/distui_1.0.8_darwin_arm64.tar.gz"
      sha256 "1a526f8454ef5cfb21de2c806dbb3f98c9dc5dfbde147020532f103aa52f01e2"

      def install
        bin.install "distui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v1.0.8/distui_1.0.8_linux_amd64.tar.gz"
      sha256 "acafba8ba391d8f969126450580e1136cdcf1bc6f990fd0ed07a8137c730596b"
      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v1.0.8/distui_1.0.8_linux_arm64.tar.gz"
      sha256 "45b836b31020b8dd355a1c2d5234c31f0649189aadd9dfdcc884b168692313f9"
      def install
        bin.install "distui"
      end
    end
  end

  test do
    system "#{bin}/distui", "--version"
  end
end
