# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distui < Formula
  desc "distui"
  homepage "https://github.com/willyv3/distui"
  version "0.0.31"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/willyv3/distui/releases/download/v0.0.31/distui_0.0.31_darwin_amd64.tar.gz"
      sha256 "96a5d9aed7409ea768c0983cc469161fb6c734e1c12cfbb0f906dc779d2f487f"

      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/willyv3/distui/releases/download/v0.0.31/distui_0.0.31_darwin_arm64.tar.gz"
      sha256 "2d819a498a76a20aa9535909fd7f115d09aba5c660e41502d2fa91c654aeaea9"

      def install
        bin.install "distui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.31/distui_0.0.31_linux_amd64.tar.gz"
      sha256 "8032c033969e84dd1e50a3061e8eb22a943fc3b97ecfacb0357cd8bc3c01633e"
      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.31/distui_0.0.31_linux_arm64.tar.gz"
      sha256 "9f6c1629e2e017a66163442bcfe00c4c835669043654776d9d44fb43b423a554"
      def install
        bin.install "distui"
      end
    end
  end

  test do
    system "#{bin}/distui", "--version"
  end
end
