# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distui < Formula
  desc "distui"
  homepage "https://github.com/willyv3/distui"
  version "0.0.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/willyv3/distui/releases/download/v0.0.35/distui_0.0.35_darwin_amd64.tar.gz"
      sha256 "628a39741862f584a2151726a077cb2210a61d869a882f26ba3ebc1806516db5"

      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/willyv3/distui/releases/download/v0.0.35/distui_0.0.35_darwin_arm64.tar.gz"
      sha256 "d2e69bf1667a3778685095bbd20e43ddfeec0a673e9a72443109d2e0755ee5d2"

      def install
        bin.install "distui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.35/distui_0.0.35_linux_amd64.tar.gz"
      sha256 "839bce8d846f007a18c64acf8fd1ca0496256ba093974392dbb3162dc3c67898"
      def install
        bin.install "distui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/distui/releases/download/v0.0.35/distui_0.0.35_linux_arm64.tar.gz"
      sha256 "4f4c5ffc2b1e4466ad7a7c1c0943797b57a538b4183bce47ea50b7b08fa6a33e"
      def install
        bin.install "distui"
      end
    end
  end

  test do
    system "#{bin}/distui", "--version"
  end
end
