# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lofitui < Formula
  desc "Terminal UI for playing YouTube lofi streams with mpv"
  homepage "https://github.com/willyv3/lofitui-go"
  version "0.1.1"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.1/lofitui_0.1.1_darwin_amd64.tar.gz"
      sha256 "75a4e39ee7f689243e23462ede3d7553db7f15846546a60ed8597eb8b6a2a5f9"

      def install
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.1/lofitui_0.1.1_darwin_arm64.tar.gz"
      sha256 "483ef7c4418659495cfa6fddd867b8fe9d831a667bf143dc95c8ea954400de50"

      def install
        bin.install "lofitui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.1/lofitui_0.1.1_linux_amd64.tar.gz"
      sha256 "55ca854a4915fc50d6d033ee09108eec30d82203a06f40402184de2660bfd38f"
      def install
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.1/lofitui_0.1.1_linux_arm64.tar.gz"
      sha256 "62d1d67df968d6d43369798040a66ae6e2a8aa9b011528dc2c2222b21d277f20"
      def install
        bin.install "lofitui"
      end
    end
  end

  def caveats
    <<~EOS
      ░█░░░█▀█░█▀▀░▀█▀░▀█▀░█░█░▀█▀
      ░█░░░█░█░█▀▀░░█░░░█░░█░█░░█░
      ░▀▀▀░▀▀▀░▀░░░▀▀▀░░▀░░▀▀▀░▀▀▀

      Terminal UI for lofi streams!

      Quick start:
        lofitui

      Key bindings:
        m - Manage presets
        c - Custom URL
        q - Quit

      Config location:
        ~/.config/lofitui/config.json

      Dependencies installed:
        • mpv (video player)
        • yt-dlp (stream extractor)
    EOS
  end

  test do
    system "#{bin}/lofitui", "--version"
  end
end
