# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lofitui < Formula
  desc "Terminal UI for playing YouTube lofi streams with mpv"
  homepage "https://github.com/willyv3/lofitui-go"
  version "0.1.4"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.4/lofitui_0.1.4_darwin_amd64.tar.gz"
      sha256 "cb5be2b3d51b563d04d41a4a14b4e7ae354c1c985b697e137a9a9ec9a9b1a5a7"

      define_method(:install) do
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.4/lofitui_0.1.4_darwin_arm64.tar.gz"
      sha256 "8db2e367b5da1a8b4e89a3a4043ec31bbc318d97719cb0dbb77e5f4d4153f516"

      define_method(:install) do
        bin.install "lofitui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.4/lofitui_0.1.4_linux_amd64.tar.gz"
      sha256 "1664d382ec8c5c93da80684665fb13657f7216740d0810eaa31a20c2488f2def"
      define_method(:install) do
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.4/lofitui_0.1.4_linux_arm64.tar.gz"
      sha256 "c897574699363ed815bf221e6962fac1125732f644c7f1a22f4e00c20be94217"
      define_method(:install) do
        bin.install "lofitui"
      end
    end
  end

  def caveats
    <<~EOS
      ░█░░░█▀█░█▀▀░▀█▀░▀█▀░█░█░▀█▀
      ░█░░░█░█░█▀▀░░█░░░█░░█░█░░█░
      ░▀▀▀░▀▀▀░▀░░░▀▀▀░░▀░░▀▀▀░▀▀▀

      Terminal UI for lofi streams!

      Quick start:
        lofitui

      Key bindings:
        m - Manage presets
        c - Custom URL
        q - Quit

      Config location:
        ~/.config/lofitui/config.json

      Dependencies installed:
        • mpv (video player)
        • yt-dlp (stream extractor)
    EOS
  end

  test do
    system "#{bin}/lofitui", "--version"
  end
end
