# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lofitui < Formula
  desc "Terminal UI for playing YouTube lofi streams with mpv"
  homepage "https://github.com/willyv3/lofitui-go"
  version "0.1.0"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.0/lofitui_0.1.0_darwin_amd64.tar.gz"
      sha256 "7b3ca2dcb8e691420bb6b10ff86240281e33f0c2f5619f6d3548f45e16f81e1a"

      def install
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.0/lofitui_0.1.0_darwin_arm64.tar.gz"
      sha256 "fc28a97388c27caae8ad2b2b577591e31f0a23272632c7b41fc92d702cf1dde2"

      def install
        bin.install "lofitui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.0/lofitui_0.1.0_linux_amd64.tar.gz"
      sha256 "b037a950e8df8ff66c6b20b6f4329744fc1d934101c6a1f83b5b512998bb839c"
      def install
        bin.install "lofitui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/lofitui/releases/download/v0.1.0/lofitui_0.1.0_linux_arm64.tar.gz"
      sha256 "1527f76fe59be749b84abd2b6bbe5ab9a4c704944bd1924963214bac43445ca5"
      def install
        bin.install "lofitui"
      end
    end
  end

  def caveats
    <<~EOS
      ░█░░░█▀█░█▀▀░▀█▀░▀█▀░█░█░▀█▀
      ░█░░░█░█░█▀▀░░█░░░█░░█░█░░█░
      ░▀▀▀░▀▀▀░▀░░░▀▀▀░░▀░░▀▀▀░▀▀▀

      Terminal UI for lofi streams!

      Quick start:
        lofitui

      Key bindings:
        m - Manage presets
        c - Custom URL
        q - Quit

      Config location:
        ~/.config/lofitui/config.json

      Dependencies installed:
        • mpv (video player)
        • yt-dlp (stream extractor)
    EOS
  end

  test do
    system "#{bin}/lofitui", "--version"
  end
end
