# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MouserCli < Formula
  desc "CLI for Mouser Electronics"
  homepage "https://github.com/WillyV3/mouser-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/mouser-cli/releases/download/v0.1.0/mouser-cli_darwin_amd64.tar.gz"
      sha256 "e0a2038fc9f8c1e047e1cdf6d1ce62476bb330218b1252140a274bbee610c8b5"

      def install
        bin.install "mouser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/mouser-cli/releases/download/v0.1.0/mouser-cli_darwin_arm64.tar.gz"
      sha256 "00be2be8f3394ce787eecf90c766225bda374a9fee911c126874ca2c98b400f2"

      def install
        bin.install "mouser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/mouser-cli/releases/download/v0.1.0/mouser-cli_linux_amd64.tar.gz"
      sha256 "fdda217f7b062820d2f97544b5adeb445f57a1974167591d68883e608d952212"
      def install
        bin.install "mouser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/mouser-cli/releases/download/v0.1.0/mouser-cli_linux_arm64.tar.gz"
      sha256 "0ff61ea4474a39dcf87e84cf9a878fe3378aa40fbf1d2f0dc50b3a58320e32b2"
      def install
        bin.install "mouser"
      end
    end
  end
end
