# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VinwWorkspace < Formula
  desc "VINW Workspace - Interactive TMUX session manager"
  homepage "https://github.com/WillyV3/vinw-workspace"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.4/vinw-workspace_0.0.4_darwin_amd64.tar.gz"
      sha256 "50b995d9f615d7f66eb849daefce43f865d792b6f97a80c95ee88b52ee169a6a"

      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.4/vinw-workspace_0.0.4_darwin_arm64.tar.gz"
      sha256 "dd891e03f4176571a4604da978fc8d630f96a3cc653a40e33dc5724bdbd685dc"

      def install
        bin.install "vinw-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.4/vinw-workspace_0.0.4_linux_amd64.tar.gz"
      sha256 "8c0a1c57c18f48641c3556d7cf4f25f3c386f803088474e01e0baf98d1e8183f"
      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.0.4/vinw-workspace_0.0.4_linux_arm64.tar.gz"
      sha256 "2fbeb3538863041e3de1e5f6659fdeaec06534d39bd3db976af53dc01d8b4e94"
      def install
        bin.install "vinw-workspace"
      end
    end
  end

  test do
    system "#{bin}/vinw-workspace", "--version"
  end
end
