# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VinwWorkspace < Formula
  desc "vinw-workspace"
  homepage "https://github.com/WillyV3/vinw-workspace"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.1.1/vinw-workspace_0.1.1_darwin_amd64.tar.gz"
      sha256 "b30647b8f0eb3e130de8fb183862330a4f0e95d58fe3e3002aa7cd6e191352f2"

      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.1.1/vinw-workspace_0.1.1_darwin_arm64.tar.gz"
      sha256 "77db609a5c9e9bd1102b79f5a9c0d647b56a37b7416c5729c042e0b181045051"

      def install
        bin.install "vinw-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.1.1/vinw-workspace_0.1.1_linux_amd64.tar.gz"
      sha256 "7c947000f71fc566ad40dcc9a0a4c126cd97ba66de8b1ffdd5a884979c5e35d9"
      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillyV3/vinw-workspace/releases/download/v0.1.1/vinw-workspace_0.1.1_linux_arm64.tar.gz"
      sha256 "64883bfa21ace3dfd0eeccfc56414f66d738584ea0289e2d13b759106f5ba63d"
      def install
        bin.install "vinw-workspace"
      end
    end
  end

  test do
    system "#{bin}/vinw-workspace", "--version"
  end
end
