# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VinwWorkspace < Formula
  desc "vinw-workspace"
  homepage "https://github.com/WillyV3/vinw-workspace"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/willyv3/vinw-workspace/archive/v0.2.1.tar.gz"
      sha256 "5d53f53b4a801a03bfd6abd5ebb8ab1f14fd1d165187f3bee43c000572799d72"

      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/willyv3/vinw-workspace/archive/v0.2.1.tar.gz"
      sha256 "5d53f53b4a801a03bfd6abd5ebb8ab1f14fd1d165187f3bee43c000572799d72"

      def install
        bin.install "vinw-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/vinw-workspace/archive/v0.2.1.tar.gz"
      sha256 "5d53f53b4a801a03bfd6abd5ebb8ab1f14fd1d165187f3bee43c000572799d72"
      def install
        bin.install "vinw-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/willyv3/vinw-workspace/archive/v0.2.1.tar.gz"
      sha256 "5d53f53b4a801a03bfd6abd5ebb8ab1f14fd1d165187f3bee43c000572799d72"
      def install
        bin.install "vinw-workspace"
      end
    end
  end

  test do
    system "#{bin}/vinw-workspace", "--version"
  end
end
